### PR TITLE
Ignore DotSettings files generated by Resharper

### PR DESCRIPTION
**Pull request by maxime-poulain**
Resharper generates a configuration file when enabling some features on projects.
Enabling support for string localization generates this kind of file.

Example:
```xml
<wpf:ResourceDictionary xml:space="preserve" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:s="clr-namespace:System;assembly=mscorlib" xmlns:ss="urn:shemas-jetbrains-com:settings-storage-xaml" xmlns:wpf="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
    <s:String x:Key="/Default/CodeEditing/Localization/Localizable/@EntryValue">Yes</s:String>
    <s:String x:Key="/Default/CodeEditing/Localization/LocalizableInspector/@EntryValue">Pessimistic</s:String>
</wpf:ResourceDictionary>
`

### CODE REVIEW

**Review by chastelain — COMMENTED** [review]
Tu est sure de vouloir dégager ça du source control? Faudrait pas p-e le paramétrer?

`The .dotSettings contains project or solution specific settings that can be shared with the team, e.g. naming standards or braces layout. If you wish to share these amongst teams then the file should be included.`

**Comment by maxime-poulain** [comment]
> Tu est sure de vouloir dégager ça du source control? Faudrait pas p-e le paramétrer?
> 
> `The .dotSettings contains project or solution specific settings that can be shared with the team, e.g. naming standards or braces layout. If you wish to share these amongst teams then the file should be included.`

Knew for once it would not be a waste to ask your 2 cents.

Hm that's a bit of a problem, if you enable localization in rsharper, for example, it can be super annoying for some people.

image

Are you sure that what gets shared is an xxxx.csproj.dotsettings and not just something like mysuperfile.dotsettings ?

**Comment by chastelain** [comment]
Je découvre en même temps que toi 😄 

https://www.jetbrains.com/help/resharper/Sharing_Configuration_Options.html#solution-personal-layer

Si je comprends bien, les settings personnels c'est ceux genre `[.csproj|.sln].DotSettings.user`, d'après la doc du lien là-dessus:
`The corresponding settings file <SolutionName>.sln.DotSettings.user is saved in the solution folder. You should not add it to your VCS.`

https://www.jetbrains.com/help/resharper/Sharing_Configuration_Options.html#managing
`By default, you can share ReSharper settings per solution using the 'Solution team shared' layer — the only thing you need to do is to put the *.dotSettings file under version control.`

**Comment by maxime-poulain** [comment]
J'ai foutu dans mon git ignore personel le ficher.

Tu pourrais activer la localization poru test ? 

Right click sur un project -> enable project item property -> et la tu set, on va voir si a te créé un personnel ou ?

**Pull request closed without merging**
