### PR TITLE
Fill Readme with info for UserAdmin (and Showcase)

### PR DESCRIPTION
**Pull request by Victor-van-Duijnen**
A Draft PR in order to start writting the readme for the project (it's kind of overdue).
Right now it is pretty rough and missing information but it's a start. 
I have let the Showcase section empty, maybe we can talk about it @CelineMarique  @maxime-poulain ?

### CODE REVIEW

**Comment by CelineMarique** [comment]
> A Draft PR in order to start writting the readme for the project (it's kind of overdue). Right now it is pretty rough and missing information but it's a start. I have let the Showcase section empty, maybe we can talk about it @CelineMarique @maxime-poulain ?

Yes, i have some tasks to fill the showcase readme file

**Comment by LievenPraet** [comment]
Just a small comment: the file `appsettings.Local.json` should be named `appsettings.local.json` so it's in all lower case.

**Review by LievenPraet — COMMENTED** [review]
Just a small comment: the file `appsettings.Local.json` should be named `appsettings.local.json` so it's in all lower case.

**Comment by Victor-van-Duijnen** [comment]
@LievenPraet  Why do you reckon we should [switch from `appsettings.Local.json` to `appsettings.local.json` ](https://github.com/smartcoop/smart-cfa/pull/69#pullrequestreview-940582172)? it has been done like that to follow Microsoft convention with its `appsettings.Development.json` , `appsettings.Staging.json`, ....

**Review by CelineMarique — APPROVED** [review]

**Comment by Victor-van-Duijnen** [comment]
@LievenPraet @CelineMarique @maxime-poulain May I squash that into main? I have several things to add to the readme in other PR's I would like to add  to that reeadme so having a basis to write it would be good (also to avoid conflicts).

**Pull request merged**
